#configuracao do bd
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = topicos1
quarkus.datasource.password = 123456
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/topicos1db

#desabilitar o docker
quarkus.devservices.enabled=false

quarkus.hibernate-orm.database.generation=drop-and-create
#quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true

# Configuração do Keycloak para o Quarkus proteger a API
quarkus.oidc.auth-server-url=http://localhost:8180/realms/xadrez-e-comerce
quarkus.oidc.client-id=backend-api
quarkus.oidc.application-type=service

quarkus.oidc.credentials.secret=jOMaZxFV2yr83XoTNIwoFnObpn8cRxKf

# Configuração para o Swagger-UI (SmallRye) liberar o botão de autenticação
quarkus.smallrye-openapi.security-scheme=oidc
quarkus.swagger-ui.oauth-client-id=backend-api

quarkus.keycloak.admin-client.server-url=http://localhost:8180

# Nome do seu Realm
quarkus.keycloak.admin-client.realm=xadrez-e-comerce

# Credenciais do Client que você configurou no Passo 1
quarkus.keycloak.admin-client.client-id=backend-api
quarkus.keycloak.admin-client.client-secret=jOMaZxFV2yr83XoTNIwoFnObpn8cRxKf
quarkus.keycloak.admin-client.grant-type=CLIENT_CREDENTIALS

# Nome da role de admin usada pela aplicação
keycloak.app.role-name=ADMIN