#configuracao do bd
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = topicos1
quarkus.datasource.password = 123456
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/topicos1db

#desabilitar o docker
quarkus.devservices.enabled=false

quarkus.hibernate-orm.database.generation=drop-and-create
#quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true

# Configuração do Keycloak para o Quarkus proteger a API
quarkus.oidc.auth-server-url=http://localhost:8180/realms/xadrez-e-comerce
quarkus.oidc.client-id=backend-api
quarkus.oidc.application-type=service

# Configuração para o Swagger-UI (SmallRye) liberar o botão de autenticação
quarkus.smallrye-openapi.security-scheme=oidc
quarkus.smallrye-openapi.oidc.client-id=backend-api