@startuml DiagramaCasoDeUso
left to right direction

actor Administrador

rectangle SistemaAdministrativoXadrez {

    usecase "Gerenciar Peças" as UC1
    usecase "Gerenciar Kits de Peças" as UC2
    usecase "Gerenciar Tabuleiros" as UC3
    usecase "Gerenciar Relógios" as UC4
    usecase "Gerenciar Jogos Completos" as UC5
    usecase "Gerenciar Materiais" as UC6
    usecase "Gerenciar Fabricantes" as UC7

    usecase "Definir Estoque do Jogo Completo" as UC10
    usecase "Vincular Relógio ao Jogo Completo" as UC11
}

Administrador --> UC1
Administrador --> UC2
Administrador --> UC3
Administrador --> UC4
Administrador --> UC5
Administrador --> UC6
Administrador --> UC7
Administrador --> UC10
Administrador --> UC11

' Relações

UC5 .> UC10 : <<include>>
UC11 .> UC5 : <<extend>>

@enduml
